#!/bin/bash

set -e

# Bundle install under the vendor directory

  function bundle_install_at {
    local gem_path=$1
    if [ -f $gem_path/Gemfile ]; then
      cd $gem_path
      echo
      echo "Start bundle installing to $gem_path"
      bundle install --path vendor/bundle
    fi
  }


# Install bundle exec warppers to bundlizer exec bin

  function install_bundle_exec_wrappers {
    local gem_path=$1
    for bin in `get_gem_bin_files $gem_path`; do
      bin_path=$BUNDLES/bin/$bin
      create_bundle_exec_wrapper $gem_path $bin > $bin_path
      chmod +x $bin_path
      echo "It was installed \`$bin\` into $bin_path"
    done
}


# Return RubyGems executable file list

  function get_gem_bin_files {
    local bindir=$1/bin
    [ -d $bindir ] && ls $bindir
  }


# Create a `bundle exec` wrapper script

  function create_bundle_exec_wrapper {
    local gem_path=$1
    local bin=$2
    cat << EOF
#!/bin/sh

cd $gem_path
bundle exec $bin \$*
EOF
  }


# Install repository

  function install {
    if [[ $1 =~ ^.+/.+$ ]]; then
      local dirname=`echo $1 | cut -d '/' -f2`
      local url="git://github.com/$1.git"
      cd $BUNDLES
      git clone $url
      bundle_install_at $BUNDLES/$dirname
      install_bundle_exec_wrappers $BUNDLES/$dirname
    else
       warn "Option Format error. See '$bin_name help'"
    fi
  }
