#!/bin/bash

set -e

# Bundle update under the vendor directory

  function bundle_update_at {
    local gem_path=$1
    if [ -f $gem_path/Gemfile ]; then
      cd $gem_path
      echo
      echo "Start bundle update to $gem_path"
      git pull origin master
      bundle update
    fi
  }


# Update repository

  function update {
    local target=$1
    case $target in
      '' | 'all')
        for gem_path in `ls -d $BUNDLES/*`; do
          bundle_update_at $gem_path
          install_bundle_exec_wrappers $gem_path
        done
        ;;
      *)
        [ ! -d $BUNDLES/$target ] && _warn "$bin_name: no such target \"$target\""
        bundle_update_at $BUNDLES/$target
        install_bundle_exec_wrappers $BUNDLES/$target
        ;;
    esac
  }
