#!/bin/sh

set -e

# Define constants

    readonly PREFIX=$(cd $(dirname $0)/.. && pwd)
    readonly BUNDLES=$PREFIX/bundles


# Display installed bundler apps

    list() {
      for app in `ls $BUNDLES`; do
        echo "$app (`ls $BUNDLES/$app/bin | tr '\012' ',' | sed 's/,$//g'`)"
      done
    }


list $@

exit 0
