#!/bin/sh

set -e


# Define constants

    readonly BUNDLES="$(cd $(dirname $0)/.. && pwd)/bundles"


# Manage dependencies

    depends() {
      local app=$1
      if [ ! -d $BUNDLES/$app ]; then
        echo "bundlizer: no such app '$app'"
        return 1
      fi

      show_dependencies_at $BUNDLES/$app
    }


# Show dependencies under the bundlizer apps directory

    show_dependencies_at() {
      local app_path=$1
      if [ -f $app_path/Gemfile ]; then
        cd $app_path
        bundle show
      fi
      if [ -d $app_path/specifications ]; then
        GEM_PATH= GEM_HOME=$app_path gem list
      fi
    }



depends $@
