#!/bin/sh

set -e


# Define constants

    readonly BUNDLES=$(cd $(dirname $0)/.. && pwd)$PREFIX/bundles


# Display installed bundlizer apps

    list() {
      local verbose=''
      case $1 in
        '-v' | '--verbose')
          verbose=1
          ;;
      esac

      echo "Gem/Bundler apps installed by the Bundlizer:"
      echo

      [ ! -d $BUNDLES ] && return

      for app in $(ls $BUNDLES); do
        [ ! $verbose ] && {
          echo $app
          continue
        }

        if [ -d $BUNDLES/$app/.git ]; then
          echo " * $app ($(cd $BUNDLES/$app; git remote show origin -n | grep "Fetch URL" | cut -d' ' -f5))"
        fi

        if [ -d $BUNDLES/$app/specifications ]; then
          echo " * $app (rubygems.org: http://rubygems.org/gems/$app)"
        fi

        if [ -d $BUNDLES/$app/bin ]; then
          echo "     apps: $(ls $BUNDLES/$app/bin | tr '\012' ',' | sed 's/,$//g')"
        fi
      done
    }



list $@
