#!/bin/sh

set -e


# Define constants

    readonly BUNDLES=$(cd $(dirname $0)/.. && pwd)$PREFIX/bundles


# Display outdated bundlizer apps

    outdated() {
      [ ! -d $BUNDLES ] && return

      for app in $(ls $BUNDLES); do
        echo "----- $app"

        if [ -f $BUNDLES/$app/Gemfile ]; then
          bundle outdated
        fi

        if [ -d $BUNDLES/$app/specifications ]; then
          GEM_PATH=$BUNDLES/$app gem outdated -r
        fi
      done
    }



outdated $@
