#!/bin/bash

set -e


# Define constants

    readonly PREFIX=$(cd $(dirname $0)/.. && pwd)
    readonly BUNDLES=$PREFIX/bundles
    readonly COMMANDS=$PREFIX/libexec

    readonly bin_name=`basename $0`


# Check requirements

    initialize() {
      if ! type gem &> /dev/null; then
        echo 'RubyGems not found'
        exit 1
      fi

      if ! type bundle &> /dev/null; then
        echo 'Bundler not found'
        exit 1
      fi

    }


# Display the Bundlizer help

    usage() {
      echo "Usage: $bin_name COMMAND [command-specific-options]"
      echo
      echo 'Bundler apps commands:'
      echo '  install   user/repository  # git clone git://github.com/user/repository, and bundle install'
      echo '  update    [app]            # named app git pull and bundle update(or all update)'
      echo '  uninstall app              # uninstall the app'
      echo '  list                       # display installed bundler apps'
      echo
      echo 'Bundlizer commands:'
      echo '  upgrade                    # upgrade the Bundlizer'
      echo '  help, --help               # display usage'
      echo '  version                    # display version'
      exit 0
    }


# Start the Bundlizer

    bundlizer() {

      local command=$1
      shift 1

      [ -z $command ] && usage || {
        initialize

        case $command in
        'help' | '--help')
          usage
          ;;
        *)
          if [ -f "$COMMANDS/bundlizer-$command" ]; then
            exec "$COMMANDS/bundlizer-$command" $@
          else
            echo "$bin_name: Could not find command \"$command\"."
            echo "See '$bin_name help' for more information on a specific command"
            exit 1
          fi
          ;;
        esac

        exit 0
      }
    }


bundlizer $@
