#!/bin/sh

set -e


# Define constants

    readonly BUNDLES=$(cd $(dirname $0)/.. && pwd)$PREFIX/bundles


# Run installed bundlizer apps

    run() {
      if echo $1 | egrep '^.+/.+$' >/dev/null; then
        local app=$(echo $1 | cut -d '/' -f1)
        local command=$(echo $1 | cut -d '/' -f2)

        shift

        local app_path=$BUNDLES/$app

        # Switch context for `bundlizer use` command
        #   [sstephenson/rbenv - GitHub #rbenv shell](https://github.com/sstephenson/rbenv#rbenv-shell)
        if [ -f $app_path/.ruby-version ]; then
          export RBENV_VERSION=$(cat $app_path/.ruby-version)
        fi

        if [ -f $app_path/Gemfile ]; then
          RUBYOPT="-I$app_path/lib -r$app_path/bundle/bundler/setup" $app_path/bin/$command "$@"
        fi

        if [ -d $app_path/specifications ]; then
          GEM_PATH=$app_path:$(gem environment gempath) GEM_HOME= PATH=$app_path/bin:$PATH $command "$@"
        fi
      else
        echo "Option Format error. See 'bundlizer help'"
        return 1
      fi
    }



run "$@"
