#!/bin/sh

set -e


# Define constants

    readonly BUNDLES=$(cd $(dirname $0)/.. && pwd)$PREFIX/bundles


# Run installed bundlizer apps

    run() {
      if echo $1 | egrep '^.+/.+$' >/dev/null; then
        local app=$(echo $1 | cut -d '/' -f1)
        local command=$(echo $1 | cut -d '/' -f2)

        shift

        local app_path=$BUNDLES/$app
        if [ -f $app_path/Gemfile ]; then
          RUBYOPT="-I$app_path/lib -r$app_path/bundle/bundler/setup" $app_path/bin/$command $@
        fi
        if [ -d $app_path/specifications ]; then
          GEM_PATH=$app_path:$(gem environment gempath) GEM_HOME= PATH=$app_path/bin:$PATH $command $@
        fi
      else
        echo "Option Format error. See 'bundlizer help'"
        return 1
      fi
    }



run $@
