#!/bin/sh

set -e


# Define constants

    readonly BUNDLES="$(cd $(dirname $0)/.. && pwd)/bundles"


# Update repository

    update() {
      local app=$1
      case $app in
      '' | 'all')
        for app_path in $(ls -d $BUNDLES/*); do
          update_at $app_path
        done
        ;;
      *)
        if [ ! -d $BUNDLES/$app ]; then
          echo "bundlizer: no such app '$app'"
          return 1
        fi
        update_at $BUNDLES/$app
        ;;
      esac
    }


# Update under the vendor directory

    update_at() {
      local app_path=$1
      if [ -f $app_path/Gemfile ]; then
        cd $app_path
        echo
        echo "Start bundle update to $app_path"
        git reset --hard
        git pull origin master
        bundle install
      fi
      if [ -d $app_path/specifications ]; then
        echo "Start gem update to $app_path"
        GEM_PATH= GEM_HOME=$app_path gem update $(basename $app_path) $@
      fi
    }



update $@
