#!/bin/sh

set -e


# Define constants

    readonly PREFIX=$(cd $(dirname $0)/.. && pwd)
    readonly BUNDLES=$PREFIX/bundles
    readonly APPS=$PREFIX/apps


# Uninstall Bundler apps

    uninstall() {
      local app=$1

      if [ -z $app ]; then
        echo "Option error. See 'bundlizer help'"
        return 1
      fi

      if [ -d $BUNDLES/$app ] ; then
        /bin/echo -n "uninstall: remove app '$app'? (yes/no) "
        read input

        [ ! $input = 'yes' ] && return 1

        local app_path=$BUNDLES/$app

        for bin in $(get_app_bin_files $app_path); do
          echo "rm -f $APPS/$bin"
          rm -f $APPS/$bin
        done

        echo "rm -rf $app_path"
        rm -rf $app_path

        echo "It was Uninstalled '$app'"
      fi
    }


# Return Bundler apps executable file list

    get_app_bin_files() {
      local bindir=$1/bin
      [ -d $bindir ] && ls $bindir
    }



uninstall $@
