#!/bin/sh

set -e


# Define constants

    readonly PREFIX=$(cd $(dirname $0)/.. && pwd)
    readonly BUNDLES=$PREFIX/bundles
    readonly APPS=$PREFIX/apps


# Uninstall Bundlizer app

    uninstall() {
      local app=$1

      if [ -z $app ]; then
        echo "Option error. See 'bundlizer help'"
        return 1
      fi

      if [ -d $BUNDLES/$app ] ; then
        /bin/echo -n "uninstall: remove app '$app'? (yes/no) "
        read input

        [ ! $input = 'yes' ] && {
          echo 'OK. Nothing to do.'
          return 1
        }

        local app_path=$BUNDLES/$app

        for bin in $(get_app_bin_files $app_path); do
          echo "rm -f $APPS/$bin"
          rm -f $APPS/$bin
        done

        echo "rm -rf $app_path"
        rm -rf $app_path

        echo "It was Uninstalled '$app'"
      else
        echo "$app is not installed"
      fi
    }


# Returns Bundler/Gem apps executable file list

    get_app_bin_files() {
      local app_path=$1

      # Bundler
      if [ -f $app_path/Gemfile ]; then
        [ -d $app_path/bin ] && ls $app_path/bin
      fi

      # Gem
      if [ -d $app_path/specifications ]; then
        local app=$(echo $app_path | rev | cut -d '/' -f 1 | rev)
        GEM_PATH=$app_path:$(gem environment gempath) GEM_HOME= gem specification $app executables | tail -n +2 | tr -d - | tr -d '\n'
      fi
    }



uninstall $@
