#!/bin/sh

set -e

# Define constants

    readonly BUNDLES="$(cd $(dirname $0)/.. && pwd)/bundles"


# Update repository

    update() {
      local target=$1
      case $target in
      '' | 'all')
        for gem_path in `ls -d $BUNDLES/*`; do
          bundle_update_at $gem_path
        done
        ;;
      *)
        if [ ! -d $BUNDLES/$target ]; then
          echo "bundlizer: no such target \"$target\""
          exit 1
        fi
        bundle_update_at $BUNDLES/$target
        ;;
      esac
    }


# Bundle update under the vendor directory

    bundle_update_at() {
      local gem_path=$1
      if [ -f $gem_path/Gemfile ]; then
        cd $gem_path
        echo
        echo "Start bundle update to $gem_path"
        git reset --hard
        git pull origin master
        bundle update
      fi
    }


update $@

exit 0
