#!/bin/sh

set -e


# Define constants

    readonly BUNDLES="$(cd $(dirname $0)/.. && pwd)/bundles"


# Manage dependencies

    depends() {
      local app=$1
      shift

      if [ ! -d $BUNDLES/$app ]; then
        echo "bundlizer: no such app '$app'"
        return 1
      fi

      case "$@" in
      --add-gem*)
        shift
        add_dependent_gem_to $BUNDLES/$app "$@"
        ;;
      *)
        show_dependencies_at $BUNDLES/$app
        ;;
      esac
    }

# Add dependent gem to the specific app

    add_dependent_gem_to() {
      local app_path=$1
      shift

      if [ -f $app_path/Gemfile ]; then
        echo "Sorry, $(basename $app_path) is Bundler format project."
        echo '--add-gem option has enabled at RubyGems only.'
        return 1
      fi

      gem install -i $app_path -E "$@"
    }

# Show dependencies under the bundlizer apps directory

    show_dependencies_at() {
      local app_path=$1

      if [ -f $app_path/Gemfile ]; then
        cd $app_path
        bundle show
      fi

      if [ -d $app_path/specifications ]; then
        GEM_PATH= GEM_HOME=$app_path gem list
      fi
    }



depends "$@"
