#!/bin/sh

set -e


# Define constants

    readonly PREFIX=$(cd $(dirname $0)/.. && pwd)
    readonly BUNDLES=$PREFIX/bundles
    readonly APPS=$PREFIX/apps


# Install Bundler apps

    install() {
      check_bundles_dir_exists && {
        if echo $1 | egrep '^(https|http|git)?://.+$' > /dev/null; then
          local url=$1
          local app=$(echo $1 | rev | cut -d '/' -f1 | rev | sed -e s/.git$//)
          cd $BUNDLES
          git clone $url
          bundle_install_at $BUNDLES/$app
          install_bundlizer_run_wrappers $BUNDLES/$app
        elif echo $1 | egrep '^.+/.+$' >/dev/null; then
          local user=$(echo $1 | cut -d '/' -f1)
          local app=$(echo $1 | cut -d '/' -f2)
          local url="git://github.com/$user/$app.git"
          cd $BUNDLES
          git clone $url
          bundle_install_at $BUNDLES/$app
          install_bundlizer_run_wrappers $BUNDLES/$app
        else
          local app=$1
          shift
          cd $BUNDLES
          echo "Searching in RubyGems..."
          gem specification $app -r 1>/dev/null && {
            gem install -E $app -i $BUNDLES/$app $@
            install_bundlizer_run_wrappers $BUNDLES/$app
          }
        fi
      }
    }


# Check if bundles directory exists

    check_bundles_dir_exists() {
      [ -d $BUNDLES ] && return 0
      mkdir $BUNDLES
    }


# Bundle install under the vendor directory

    bundle_install_at() {
      local app_path=$1
      local rbenv_version=''
      if [ -f $app_path/Gemfile ]; then
        cd $app_path
        echo

        echo "Start bundle installing to $app_path"

        if [ -f $app_path/.ruby-version ]; then
          rbenv_version=$(cat $app_path/.ruby-version)
        fi

        RBENV_VERSION=$rbenv_version bundle install --standalone --without development:test
      fi
    }


# Install `bundlizer run` warppers to bundlizer apps directory

    install_bundlizer_run_wrappers() {
      check_apps_dir_exists && {
        local app_path=$1
        for bin in $(get_app_bin_files $app_path); do
          bin_path=$APPS/$bin
          create_bundlizer_run_wrapper $app_path $bin > $bin_path
          chmod +x $bin_path
          echo "It was installed '$bin' into $bin_path"
        done
      }
    }


# Check if bundler apps directory exists

    check_apps_dir_exists() {
      [ -d $APPS ] && return 0
      mkdir $APPS
    }


# Returns Bundler/Gem apps executable file list

    get_app_bin_files() {
      local app_path=$1

      # Bundler
      if [ -f $app_path/Gemfile ]; then
        if [ -d $app_path/exe ]; then
          ls $app_path/exe
        elif [ -d $app_path/bin ]; then
          ls $app_path/bin
        fi
      fi

      # Gem
      if [ -d $app_path/specifications ]; then
        local app=$(echo $app_path | rev | cut -d '/' -f 1 | rev)
        GEM_PATH=$app_path:$(gem environment gempath) GEM_HOME= gem specification $app executables | tail -n +2 | tr -d - | tr -d '\n'
      fi
    }


# Create a `bundlizer run` wrapper script

    create_bundlizer_run_wrapper() {
      local app=$(basename $1)
      local bin=$2
      cat << EOF
#!/bin/sh

exec bundlizer run $app/$bin "\$@"
EOF
    }



install $@
